/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RestaurantRouteImport } from './routes/restaurant'
import { Route as ReserverRouteImport } from './routes/reserver'
import { Route as ReceptionRouteImport } from './routes/reception'
import { Route as KitchenRouteImport } from './routes/kitchen'
import { Route as HebergementsRouteImport } from './routes/hebergements'
import { Route as GalerieRouteImport } from './routes/galerie'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AProposRouteImport } from './routes/a-propos'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RoomRoomIdRouteImport } from './routes/room.$roomId'
import { Route as HebergementsCategoryRouteImport } from './routes/hebergements_.$category'

const RestaurantRoute = RestaurantRouteImport.update({
  id: '/restaurant',
  path: '/restaurant',
  getParentRoute: () => rootRouteImport,
} as any)
const ReserverRoute = ReserverRouteImport.update({
  id: '/reserver',
  path: '/reserver',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceptionRoute = ReceptionRouteImport.update({
  id: '/reception',
  path: '/reception',
  getParentRoute: () => rootRouteImport,
} as any)
const KitchenRoute = KitchenRouteImport.update({
  id: '/kitchen',
  path: '/kitchen',
  getParentRoute: () => rootRouteImport,
} as any)
const HebergementsRoute = HebergementsRouteImport.update({
  id: '/hebergements',
  path: '/hebergements',
  getParentRoute: () => rootRouteImport,
} as any)
const GalerieRoute = GalerieRouteImport.update({
  id: '/galerie',
  path: '/galerie',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AProposRoute = AProposRouteImport.update({
  id: '/a-propos',
  path: '/a-propos',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomRoomIdRoute = RoomRoomIdRouteImport.update({
  id: '/room/$roomId',
  path: '/room/$roomId',
  getParentRoute: () => rootRouteImport,
} as any)
const HebergementsCategoryRoute = HebergementsCategoryRouteImport.update({
  id: '/hebergements_/$category',
  path: '/hebergements/$category',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/admin': typeof AdminRoute
  '/contact': typeof ContactRoute
  '/galerie': typeof GalerieRoute
  '/hebergements': typeof HebergementsRoute
  '/kitchen': typeof KitchenRoute
  '/reception': typeof ReceptionRoute
  '/reserver': typeof ReserverRoute
  '/restaurant': typeof RestaurantRoute
  '/hebergements/$category': typeof HebergementsCategoryRoute
  '/room/$roomId': typeof RoomRoomIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/admin': typeof AdminRoute
  '/contact': typeof ContactRoute
  '/galerie': typeof GalerieRoute
  '/hebergements': typeof HebergementsRoute
  '/kitchen': typeof KitchenRoute
  '/reception': typeof ReceptionRoute
  '/reserver': typeof ReserverRoute
  '/restaurant': typeof RestaurantRoute
  '/hebergements/$category': typeof HebergementsCategoryRoute
  '/room/$roomId': typeof RoomRoomIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/admin': typeof AdminRoute
  '/contact': typeof ContactRoute
  '/galerie': typeof GalerieRoute
  '/hebergements': typeof HebergementsRoute
  '/kitchen': typeof KitchenRoute
  '/reception': typeof ReceptionRoute
  '/reserver': typeof ReserverRoute
  '/restaurant': typeof RestaurantRoute
  '/hebergements_/$category': typeof HebergementsCategoryRoute
  '/room/$roomId': typeof RoomRoomIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/a-propos'
    | '/admin'
    | '/contact'
    | '/galerie'
    | '/hebergements'
    | '/kitchen'
    | '/reception'
    | '/reserver'
    | '/restaurant'
    | '/hebergements/$category'
    | '/room/$roomId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/a-propos'
    | '/admin'
    | '/contact'
    | '/galerie'
    | '/hebergements'
    | '/kitchen'
    | '/reception'
    | '/reserver'
    | '/restaurant'
    | '/hebergements/$category'
    | '/room/$roomId'
  id:
    | '__root__'
    | '/'
    | '/a-propos'
    | '/admin'
    | '/contact'
    | '/galerie'
    | '/hebergements'
    | '/kitchen'
    | '/reception'
    | '/reserver'
    | '/restaurant'
    | '/hebergements_/$category'
    | '/room/$roomId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AProposRoute: typeof AProposRoute
  AdminRoute: typeof AdminRoute
  ContactRoute: typeof ContactRoute
  GalerieRoute: typeof GalerieRoute
  HebergementsRoute: typeof HebergementsRoute
  KitchenRoute: typeof KitchenRoute
  ReceptionRoute: typeof ReceptionRoute
  ReserverRoute: typeof ReserverRoute
  RestaurantRoute: typeof RestaurantRoute
  HebergementsCategoryRoute: typeof HebergementsCategoryRoute
  RoomRoomIdRoute: typeof RoomRoomIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/restaurant': {
      id: '/restaurant'
      path: '/restaurant'
      fullPath: '/restaurant'
      preLoaderRoute: typeof RestaurantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reserver': {
      id: '/reserver'
      path: '/reserver'
      fullPath: '/reserver'
      preLoaderRoute: typeof ReserverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reception': {
      id: '/reception'
      path: '/reception'
      fullPath: '/reception'
      preLoaderRoute: typeof ReceptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kitchen': {
      id: '/kitchen'
      path: '/kitchen'
      fullPath: '/kitchen'
      preLoaderRoute: typeof KitchenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hebergements': {
      id: '/hebergements'
      path: '/hebergements'
      fullPath: '/hebergements'
      preLoaderRoute: typeof HebergementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/galerie': {
      id: '/galerie'
      path: '/galerie'
      fullPath: '/galerie'
      preLoaderRoute: typeof GalerieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/a-propos': {
      id: '/a-propos'
      path: '/a-propos'
      fullPath: '/a-propos'
      preLoaderRoute: typeof AProposRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/room/$roomId': {
      id: '/room/$roomId'
      path: '/room/$roomId'
      fullPath: '/room/$roomId'
      preLoaderRoute: typeof RoomRoomIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hebergements_/$category': {
      id: '/hebergements_/$category'
      path: '/hebergements/$category'
      fullPath: '/hebergements/$category'
      preLoaderRoute: typeof HebergementsCategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AProposRoute: AProposRoute,
  AdminRoute: AdminRoute,
  ContactRoute: ContactRoute,
  GalerieRoute: GalerieRoute,
  HebergementsRoute: HebergementsRoute,
  KitchenRoute: KitchenRoute,
  ReceptionRoute: ReceptionRoute,
  ReserverRoute: ReserverRoute,
  RestaurantRoute: RestaurantRoute,
  HebergementsCategoryRoute: HebergementsCategoryRoute,
  RoomRoomIdRoute: RoomRoomIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
